
import {
  Activity, Globe, Moon, Plus, Minus, Settings, Sun, Timer, Trash, Trash2, User, Users, Power, Zap,
  ChevronDown, ChevronUp, ChevronLeft, ChevronRight, ChevronsLeft, ChevronsRight,
  Info, Code, Radio, BarChart, Database, Server, Tv, Share2, X, Rocket,
  CheckCircle, XCircle, AlertTriangle, Check, CircleQuestionMark, CircleX, Text,
  MoreHorizontal, ArrowLeft,
  RefreshCcw, Edit, Search, Menu, BookOpen, CheckSquare, Square, Shuffle, Filter,
  Clipboard, Copy, File, Folder, Layers, Eye, Lock, Mail, Star, Heart, Download, Upload,
  type IconNode,
} from 'lucide';

const icons = {
  activity: Activity,
  'bar-chart': BarChart,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  success: CheckCircle,
  check: Check,
  question: CircleQuestionMark,
  "circle-x": CircleX,
  error: XCircle,
  warning: AlertTriangle,
  code: Code,
  database: Database,
  globe: Globe,
  info: Info,
  minus: Minus,
  moon: Moon,
  plus: Plus,
  power: Power,
  radio: Radio,
  'share-2': Share2,
  server: Server,
  settings: Settings,
  sun: Sun,
  timer: Timer,
  trash: Trash,
  tv: Tv,
  text: Text,
  user: User,
  users: Users,
  x: X,
  zap: Zap,
  rocket: Rocket,
  'more-horizontal': MoreHorizontal,
  'arrow-left': ArrowLeft,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevrons-left': ChevronsLeft,
  'chevrons-right': ChevronsRight,
  'refresh-ccw': RefreshCcw,
  'trash-2': Trash2,
  'edit': Edit,
  'search': Search,
  'menu': Menu,
  'book-open': BookOpen,
  'check-square': CheckSquare,
  'square': Square,
  'shuffle': Shuffle,
  'filter': Filter,
  'clipboard': Clipboard,
  'copy': Copy,
  'file': File,
  'folder': Folder,
  'layers': Layers,
  'eye': Eye,
  'lock': Lock,
  'mail': Mail,
  'star': Star,
  'heart': Heart,
  'download': Download,
  'upload': Upload,
} as Record<string, IconNode>;

export const iconRegistry = {
  icons
};